title: "Evenements ISH"
description: "Liste des événements passés et actuels organisés à l'Institut des Sciences Humaines"
baseurl: ""  
url: "https://evenements.ish.edu.ml"
#theme: minima 
future: true 
remote_theme: "pages-themes/hacker@v0.2.0"



plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 4
  permalink: /page:num/
