title: "Evenements ISH"
description: "Liste des événements passés et actuels organisés à l'Institut des Sciences Humaines"
baseurl: ""  
url: "https://evenements.ish.edu.ml"
#theme: minima 
future: true 
remote_theme: "pages-themes/hacker@v0.2.0"
paginate: 5  # Number of posts per page
paginate_path: "/page:num/"


plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

